name: Terraform Pipeline
on:
  workflow_dispatch:

jobs:
  terraform_plan: 
    name: Terraform plan dev
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4
      
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configurar AWS CLI usando aws configure
        run: |
          mkdir -p ~/.aws
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_STATE }} --profile remote-state-profile
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_STATE }} --profile remote-state-profile
          aws configure set region ${{ vars.AWS_REGION }} --profile remote-state-profile

          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOY }} --profile dev
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOY }} --profile dev
          aws configure set region ${{ vars.AWS_REGION }} --profile dev
    

      # - name: Configurar AWS credentials RemoteState
      #   uses: aws-actions/configure-aws-credentials@v4.1.0
      #   with:
      #     aws-region: ${{ vars.AWS_REGION }}
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STATE }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STATE }}
      #     session-name: "tf" 


      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform init
        run: |
          echo "LS" 
          ls 
          terraform init \
           -backend-config="bucket=${{ secrets.BUCKET_NAME_STATE }}" \
           -backend-config="key=${{ vars.STATE_KEY }}" \
           -backend-config="dynamodb_table=${{ vars.DYNAMO_TABLE_LOCK }}"   \
           -backend-config="region=${{ vars.AWS_REGION }}" 
           -backend-config="session_name=remote-state-profile"

      # - name: Configurar AWS credentials CLI de Deploy
      #   uses: aws-actions/configure-aws-credentials@v4.1.0
      #   with:
      #     aws-region: ${{ vars.AWS_REGION }}
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOY }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOY }}
      #     session-name: "dev" 


      - name: Terraform Plan
        run: terraform plan -var-file ./env/dev/dev.tfvars


          

          
          

   
          
